# Path to your oh-my-zsh installation.
export ZSH=$HOME/.oh-my-zsh

# Set name of the theme to load.
# Look in ~/.oh-my-zsh/themes/
# Optionally, if you set this to "random", it'll load a random theme each
# time that oh-my-zsh is loaded.
ZSH_THEME="robbyrussell"

# Uncomment the following line to use case-sensitive completion.
# CASE_SENSITIVE="true"

# Uncomment the following line to disable bi-weekly auto-update checks.
# DISABLE_AUTO_UPDATE="true"

# Uncomment the following line to change how often to auto-update (in days).
# export UPDATE_ZSH_DAYS=13

# Uncomment the following line to disable colors in ls.
# DISABLE_LS_COLORS="true"

# Uncomment the following line to disable auto-setting terminal title.
# DISABLE_AUTO_TITLE="true"

# Uncomment the following line to enable command auto-correction.
# ENABLE_CORRECTION="true"

# Uncomment the following line to display red dots whilst waiting for completion.
# COMPLETION_WAITING_DOTS="true"

# Uncomment the following line if you want to disable marking untracked files
# under VCS as dirty. This makes repository status check for large repositories
# much, much faster.
# DISABLE_UNTRACKED_FILES_DIRTY="true"

# Uncomment the following line if you want to change the command execution time
# stamp shown in the history command output.
# The optional three formats: "mm/dd/yyyy"|"dd.mm.yyyy"|"yyyy-mm-dd"
# HIST_STAMPS="mm/dd/yyyy"

# Would you like to use another custom folder than $ZSH/custom?
# ZSH_CUSTOM=/path/to/new-custom-folder

# Which plugins would you like to load? (plugins can be found in ~/.oh-my-zsh/plugins/*)
# Custom plugins may be added to ~/.oh-my-zsh/custom/plugins/
# Example format: plugins=(rails git textmate ruby lighthouse)
# Add wisely, as too many plugins slow down shell startup.

# bugfix for vim in tmux not using 256 color.
# if [[ "$OSTYPE" == "linux-gnu" ]]; then
  # if [ $TMUX ]; then
    # if [ -e /usr/share/terminfo/s/screen-256color ]; then
      # export TERM='screen-256color'
    # else
      # export TERM='screen'
    # fi;
  # else
    # if [ -e /usr/share/terminfo/x/xterm-256color ] || [ -e /usr/share/terminfo/x/xterm+256color ]; then
      # export TERM='xterm-256color'
    # else
      # export TERM='xterm'
    # fi;
  # fi;
# fi;
if [ $TMUX ]; then
  USER_TERM_PREFIX='screen'
else
  USER_TERM_PREFIX='xterm'
fi;
# in some Linux like Gentoo, `tput colors' will return 8
# so use terminfo to detect colors
# may be screen-256color, xterm-256color or xterm+256color depending on your distro
if [[ `tput colors` == "256" ]] || [ -e /usr/share/terminfo/s/screen-256color ] || [ -e /usr/share/terminfo/x/xterm-256color ] || [ -e /usr/share/terminfo/x/xterm+256color ]; then
  USER_TERM_SUFFIX='-256color'
fi;
export TERM="${USER_TERM_PREFIX}${USER_TERM_SUFFIX}"

# if we have brew installed, add brew plugin
if which brew &> /dev/null; then
  plugins=(
    $plugins
    brew
  )
fi;

# if we have git installed, add git plugin
if which git &> /dev/null; then
  plugins=(
    $plugins
    gitfast
    git-extras
    git-flow
  )
fi;

# if we have httpie installed, add httpie plugin
if which http &> /dev/null; then
  plugins=(
    $plugins
    httpie
  )
fi;

# if we have mosh installed, add mosh plugin
if which mosh &> /dev/null; then
  plugins=(
    $plugins
    mosh
  )
fi;

# if we have tmux installed, add tmux plugin
if which tmux &> /dev/null; then
  plugins=(
    $plugins
    tmux
  )
fi;

# if we are in osx, add osx only plugins
if [[ "$OSTYPE" == "darwin"* ]]; then
  plugins=(
    $plugins
    osx
  )
fi;

# set default zsh plugins
plugins=(
  $plugins
  colored-man-pages
  encode64
  extract
  sublime
  sudo
  z
  zsh_reload
  zsh-syntax-highlighting
)

# User configuration

# Uncomment following line if you use homebrew
export PATH=$HOME/bin:/usr/local/bin:/usr/local/sbin:$PATH
# export MANPATH="/usr/local/man:$MANPATH"

source $ZSH/oh-my-zsh.sh

# You may need to manually set your language environment
# export LANG=en_US.UTF-8

# Preferred editor for local and remote sessions
# if [[ -n $SSH_CONNECTION ]]; then
#   export EDITOR='vim'
# else
#   export EDITOR='mvim'
# fi

# Compilation flags
# export ARCHFLAGS="-arch x86_64"

# ssh
# export SSH_KEY_PATH="~/.ssh/dsa_id"

# Set personal aliases, overriding those provided by oh-my-zsh libs,
# plugins, and themes. Aliases can be placed here, though oh-my-zsh
# users are encouraged to define aliases within the ZSH_CUSTOM folder.
# For a full list of active aliases, run `alias`.
#
# Example aliases
# alias zshconfig="mate ~/.zshrc"
# alias ohmyzsh="mate ~/.oh-my-zsh"

# put you own alias in ~/.zshrc.alias
[ -f $HOME/.zshrc.alias ] && source $HOME/.zshrc.alias

# put you own paths in ~/.zshrc.paths
[ -f $HOME/.zshrc.paths ] && source $HOME/.zshrc.paths

# put you own sources in ~/.zshrc.sources
[ -f $HOME/.zshrc.sources ] && source $HOME/.zshrc.sources

# history | awk '{CMD[$2]++;count++;}END { for (a in CMD) print CMD[a] " " CMD[a]/count*100 "% " a;}' | grep -v "./" | column -c3 -s " " -t | sort -nr | nl | head -n10
